# The URL the site will be built for
base_url = "https://ktt-ol.github.io"
default_language = "de"

title = "Kreativität trifft Technik e.V."
description = "Website des Kreativität trifft Technik e.V."
author = "Markus Framer"

# Compilation settings
compile_sass = true
minify_html = true
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
    { name = "Serie", feed = true, paginate_by = 10 },
    { name = "Typ", feed = true, paginate_by = 10 }
]

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[markdown]
highlight_code = true
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true

[translations]
language = "Sprache"
not_found_content = "Dies sind nicht die Inhalte die ihr sucht!"
not_found = "Inhalt nicht gefunden"
locale_name = "de_DE"
publish_time = "veröffentlicht am %date% um %time% Uhr von %author%"
all = "Alle"
images = "Bilder"
arrival = "Anreise"

closed = "Geschlossen"
closing = "Schließt bald"
open = "Geöffnet"
member = "Geschlossen (Member Only)"
keyholder = "Geschlossen (Keyholder Only)"

ifs_newest = "Neuste Images From Space"
ifs_more = "Viele weitere Fotos findest du auf der %PLACEHOLDER% Seite"

[extra]
ifs_base_path = "https://www.mainframe.io/media/ifs-images"
bs_color_map = [
    "primary",
    "secondary",
    "success",
    "danger",
    "warning",
    "info",
    "light"
]

rooms = [
    { name = "spaceOpen", title = { de = "Hackspace", en = "Hackspace" } },
    { name = "machining", title = { de = "Zerspanungstechnik", en = "Machining" } },
    { name = "woodworking", title = { de = "Holzwerkstatt", en = "Woodworking" } },
    { name = "lab3dOpen", title = { de = "3D Lab", en = "3D Lab" } },
    { name = "radstelleOpen", title = { de = "Radstelle", en = "Cycling" } },
]

[languages.en]
title = "Kreativität trifft Technik e.V."
description = "Website of Kreativität trifft Technik e.V."

# Compilation settings
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
    { name = "Series", feed = true, paginate_by = 10 },
    { name = "Type", feed = true, paginate_by = 10 }
]

[languages.en.translations]
language = "Language"
not_found_content = "This is not the content you are looking for!"
not_found = "Content not found"
locale_name = "en_US"
publish_time = "published on %date% at %time% by %author%"
all = "All"
images = "Images"
arrival = "Arrival"

closed = "Closed"
closing = "Closing soon"
open = "Open"
member = "Closed (Member Only)"
keyholder = "Closed (Keyholder Only)"

ifs_newest = "Newest Images From Space"
ifs_more = "You can find more images under the %PLACEHOLDER% site"